-- Vitola Master: Expanded Cigar Encyclopedia (Seed Data)
-- Run this in your Supabase SQL Editor to populate the encyclopedia.
INSERT INTO cigars (
        brand,
        name,
        origin,
        wrapper,
        strength,
        size,
        rating,
        price,
        notes,
        description,
        tags,
        pairings
    )
VALUES -- Cuban Classics
    (
        'Partagas',
        'Serie D No. 4',
        'Cuba',
        'Colorado',
        'Full',
        'Robusto',
        94,
        '$$$',
        'Earth, spice, leather, cedar',
        'A full-bodied masterpiece. One of the most popular Cuban cigars in history.',
        ARRAY ['Cuban', 'Classic', 'Full-Bodied'],
        ARRAY ['Coffee', 'Bourbon', 'Dark Chocolate']
    ),
    (
        'Hoyo de Monterrey',
        'Epicure No. 2',
        'Cuba',
        'Colorado Claro',
        'Mild',
        'Robusto',
        93,
        '$$$',
        'Cream, hay, light cedar, sweet spice',
        'The quintessential mild Cuban cigar. Smooth and aromatic.',
        ARRAY ['Cuban', 'Mild', 'Aromatic'],
        ARRAY ['White Tea', 'Champagne', 'Chardonnay']
    ),
    (
        'Bolivar',
        'Belicoso Fino',
        'Cuba',
        'Colorado Maduro',
        'Full',
        'Campana',
        95,
        '$$$$',
        'Deep earth, coffee, strong spice',
        'Named after Simon Bolivar, this cigar is famous for its strength and complex profile.',
        ARRAY ['Cuban', 'Strong', 'Complex'],
        ARRAY ['Old Fashioned', 'Espresso', 'Stout']
    ),
    (
        'H. Upmann',
        'Sir Winston',
        'Cuba',
        'Colorado',
        'Medium',
        'Julieta No. 2',
        96,
        '$$$$$',
        'Honey, graham cracker, cedar, floral',
        'A legendary Churchill-sized cigar. Rarely seen but highly coveted by collectors.',
        ARRAY ['Cuban', 'Churchill', 'Elegant'],
        ARRAY ['Port Wine', 'Cognac', 'Aged Rum']
    ),
    (
        'Trinidad',
        'Vigia',
        'Cuba',
        'Colorado',
        'Medium',
        'Torres',
        94,
        '$$$$',
        'Honey, nutmeg, leather, earth',
        'A modern classic from Trinidad. Short and thick with a distinctive pig-tail cap.',
        ARRAY ['Cuban', 'Pigtail', 'Modern'],
        ARRAY ['Rum', 'Nutty Coffee', 'Sherry']
    ),
    -- Nicaraguan Boldness
    (
        'Alec Bradley',
        'Prensado',
        'Nicaragua',
        'Honduran Trojes',
        'Full',
        'Churchill',
        96,
        '$$$',
        'Roasted coffee, chocolate, red pepper',
        'Cigar of the Year in 2011. Box-pressed with incredible construction.',
        ARRAY ['Nicaraguan', 'Box-Pressed', 'Award-Winning'],
        ARRAY ['Rye Whiskey', 'Black Coffee', 'Dark Chocolate']
    ),
    (
        'Perdomo',
        'Reserve 10th Anniversary Champagne',
        'Nicaragua',
        'Connecticut',
        'Mild',
        'Epicure',
        92,
        '$$',
        'Honey, almond, light spice',
        'Creamy and smooth with a golden Connecticut wrapper.',
        ARRAY ['Nicaraguan', 'Mild', 'Creamy'],
        ARRAY ['Craft Beer', 'Iced Coffee', 'Sparkling Water']
    ),
    (
        'E.P. Carrillo',
        'The Pledge Prequel',
        'Nicaragua',
        'Connecticut Habano',
        'Full',
        'Robusto',
        98,
        '$$$$',
        'Licorice, black pepper, cocoa, cedar',
        'The 2020 Cigar of the Year. An explosion of flavor from start to finish.',
        ARRAY ['Nicaraguan', 'Intense', 'Award-Winning'],
        ARRAY ['Single Malt Scotch', 'Double Espresso', 'Tequila Anejo']
    ),
    (
        'Oliva',
        'Serie V Melanio',
        'Nicaragua',
        'Sumatra',
        'Full',
        'Figurado',
        96,
        '$$$',
        'Coffee, caramel, leather, black pepper',
        'Elegantly tapered and box-pressed. A smooth yet powerful smoking experience.',
        ARRAY ['Nicaraguan', 'Sumatra', 'Refined'],
        ARRAY ['Bourbon', 'Dark Chocolate', 'French Press Coffee']
    ),
    (
        'Joy de Nicaragua',
        'Antaño 1970',
        'Nicaragua',
        'Nicaraguan Criollo',
        'Full+',
        'Robusto Grande',
        93,
        '$$',
        'Black pepper, dark earth, leather',
        'Recreating the strength of the original Joya cigars from the 70s.',
        ARRAY ['Nicaraguan', 'Very Strong', 'Classic'],
        ARRAY ['Full-Bodied Red Wine', 'Strong Coffee', 'Spiced Rum']
    ),
    -- Dominican Elegance
    (
        'La Flor Dominicana',
        'Andalusian Bull',
        'Dominican Republic',
        'Ecuador Corojo',
        'Full',
        'Figurado',
        96,
        '$$$$',
        'Leather, caramel, hickory, saffron',
        'Unique shape inspired by the matadors of Spain. Bold and sweet.',
        ARRAY ['Dominican', 'Unique', 'Award-Winning'],
        ARRAY ['Spanish Brandy', 'Oolong Tea', 'Manhattan']
    ),
    (
        'Aging Room',
        'Quattro Nicaragua Maestro',
        'Nicaragua',
        'Nicaraguan',
        'Full',
        'Torpedo',
        96,
        '$$$',
        'Chocolate, coffee, black pepper, earth',
        'A Nicaraguan puro made in the Dominican Republic. Balanced and bold.',
        ARRAY ['Dominican-Link', 'Bold', 'Award-Winning'],
        ARRAY ['Bourbon', 'Nutty Coffee', 'Dark Beer']
    ),
    (
        'Ashton',
        'VSG (Virgin Sun Grown)',
        'Dominican Republic',
        'Ecuador Sumara',
        'Full',
        'Robusto',
        95,
        '$$$$',
        'Rich cedar, leather, molasses, spice',
        'A favorite among enthusiasts who enjoy powerful, sun-grown tobacco.',
        ARRAY ['Dominican', 'Intense', 'Classic'],
        ARRAY ['Spiced Rum', 'Espresso', 'Steak']
    ),
    (
        'Gurkha',
        'Cellar Reserve 15 Year',
        'Dominican Republic',
        'Criollo 1998',
        'Medium',
        'Kraken',
        91,
        '$$$',
        'Oak, chocolate, nuttiness, heavy spice',
        'Aged for 15 years, this blend is refined and complex.',
        ARRAY ['Dominican', 'Aged', 'Bold'],
        ARRAY ['Grand Marnier', 'Vanilla Latte', 'Red Wine']
    ),
    -- Variety and Boutiques
    (
        'Tatuaje',
        'Cabaiguan',
        'Nicaragua',
        'Connecticut',
        'Mild',
        'Guapos',
        94,
        '$$',
        'Almond, cedar, white pepper',
        'A Pete Johnson creation. Mild yet full of flavor.',
        ARRAY ['Nicaraguan', 'Boutique', 'Mild'],
        ARRAY ['Light Roast Coffee', 'White Wine', 'Ginger Ale']
    ),
    (
        'Warped',
        'Flor del Valle',
        'Nicaragua',
        'Corojo 99',
        'Medium',
        'Gran Reserva',
        93,
        '$$$',
        'Floral, sweet cedar, nuts, cream',
        'Inspired by old-world Cuban traditions. Very aromatic.',
        ARRAY ['Nicaraguan', 'Boutique', 'Complex'],
        ARRAY ['Green Tea', 'Sherry', 'Rum']
    ),
    (
        'RoMa Craft',
        'Cromagnon',
        'Nicaragua',
        'US Connecticut Broadleaf',
        'Full+',
        'Anthropology',
        94,
        '$$',
        'Dark chocolate, strong earth, charcoal',
        'A powerful, gritty cigar with deep, dark flavors.',
        ARRAY ['Nicaraguan', 'Boutique', 'Strong'],
        ARRAY ['Peated Scotch', 'Turkish Coffee', 'Beef Jerky']
    ),
    (
        'Foundation',
        'The Tabernacle',
        'Nicaragua',
        'Broadleaf',
        'Full',
        'Corona Gorda',
        95,
        '$$$',
        'Molasses, dark cocoa, earth, cedar',
        'A rich, chewy broadleaf wrapper over aged Nicaraguan fillers.',
        ARRAY ['Nicaraguan', 'Broadleaf', 'Rich'],
        ARRAY ['Barleywine', 'Cold Brew', 'Dark Chocolate']
    ),
    (
        'Dunbarton',
        'Sobremesa',
        'Nicaragua',
        'Ecuador Habano',
        'Medium',
        'Cervantes Fino',
        94,
        '$$$',
        'Caramel, toast, coffee, baking spice',
        'Crafted by Steve Saka. Designed for long, enjoyable conversations.',
        ARRAY ['Nicaraguan', 'Master-Blender', 'Balanced'],
        ARRAY ['Rioja Wine', 'Latte', 'Aged Tequila']
    ),
    -- More Classics to reach the count
    (
        'Cohiba',
        'Siglo VI',
        'Cuba',
        'Colorado',
        'Medium',
        'Canonazo',
        95,
        '$$$$$',
        'Creamy, cedar, bean, spice',
        'The gold standard for the modern Cuban cigar.',
        ARRAY ['Cuban', 'Iconic', 'Luxury'],
        ARRAY ['Champagne', 'Macallan 18', 'Fine Coffee']
    ),
    (
        'Montecristo',
        'No. 4',
        'Cuba',
        'Colorado',
        'Medium',
        'Mareva',
        92,
        '$$',
        'Coffee, earth, subtle vanilla',
        'The best selling cigar in the world. Reliable and balanced.',
        ARRAY ['Cuban', 'Bestseller', 'Beginner-Friendly'],
        ARRAY ['Cafe con Leche', 'White Rum', 'Almonds']
    ),
    (
        'Davidoff',
        'The Late Hour',
        'Dominican Republic',
        'Ecuador Habano',
        'Full',
        'Churchill',
        94,
        '$$$$$',
        'Oak, leather, caramel, smoke',
        'Aged in Scotch Whisky casks. Complex and intellectual.',
        ARRAY ['Dominican', 'Whisky-Aged', 'Gourmet'],
        ARRAY ['Islay Scotch', 'Dark Chocolate', 'Steak']
    ),
    (
        'Padron',
        'Serie 1926 No. 9',
        'Nicaragua',
        'Maduro',
        'Full',
        'Robusto',
        97,
        '$$$$$',
        'Cocoa, coffee, spice, sweet earth',
        'A powerhouse of flavor. Perfectly constructed.',
        ARRAY ['Nicaraguan', 'Luxury', 'Powerhouse'],
        ARRAY ['Cognac XO', 'Espresso Martini', 'Aged Porto']
    ),
    (
        'Arturo Fuente',
        'Don Carlos Eye of the Shark',
        'Dominican Republic',
        'Cameroon',
        'Medium',
        'Figurado',
        97,
        '$$$$$',
        'Nutty, cedar, sweet spice, citrus',
        'A legendary blend with a rare Cameroon wrapper.',
        ARRAY ['Dominican', 'Rare', 'Sweet'],
        ARRAY ['Earl Grey Tea', 'Sauternes', 'Walnuts']
    );
-- 25 more entries for a total of ~50
INSERT INTO cigars (
        brand,
        name,
        origin,
        wrapper,
        strength,
        size,
        rating,
        price,
        notes,
        description,
        tags,
        pairings
    )
VALUES (
        'Villiger',
        'La Libertad',
        'Nicaragua',
        'Nicaraguan Criollo',
        'Medium',
        'Gran Toro',
        91,
        '$$',
        'Pepper, leather, cedar',
        'A bold yet balanced Nicaraguan experience.',
        ARRAY ['Nicaraguan', 'Value', 'Balanced'],
        ARRAY ['Beer', 'Americano', 'Cheddar Cheese']
    ),
    (
        'Caldwell',
        'The King is Dead',
        'Dominican Republic',
        'Negrito',
        'Medium',
        'Premier',
        93,
        '$$$',
        'Chocolate, spice, earth',
        'A unique Dominican blend with a dark, oily wrapper.',
        ARRAY ['Dominican', 'Boutique', 'Unique'],
        ARRAY ['Bourbon', 'Mocha', 'Dark Fruit']
    ),
    (
        'LAtelier',
        'Selection Speciale',
        'Nicaragua',
        'Sancti Spiritus',
        'Full',
        'Lat 52',
        94,
        '$$$',
        'Nutty, spicy, sweet cedar',
        'A collaboration involving the Garcia family.',
        ARRAY ['Nicaraguan', 'Special-Edition', 'Bold'],
        ARRAY ['Rye', 'Strong Tea', 'Salted Caramel']
    ),
    (
        'Illusione',
        'Epernay',
        'Nicaragua',
        'Cafe Rosado',
        'Mild',
        'Le Ferme',
        95,
        '$$$',
        'Floral, toast, honey, cream',
        'A cigar designed to pair specifically with Champagne.',
        ARRAY ['Nicaraguan', 'Elegant', 'Refined'],
        ARRAY ['Champagne', 'White Tea', 'Almonds']
    ),
    (
        'Viaje',
        'Skull and Bones',
        'Nicaragua',
        'Various',
        'Full+',
        'Short Robusto',
        92,
        '$$$$',
        'Intense pepper, charred wood, leather',
        'A cult classic brand known for small-batch, powerful releases.',
        ARRAY ['Nicaraguan', 'Boutique', 'Very Strong'],
        ARRAY ['Peated Scotch', 'Strong Coffee', 'Spicy Food']
    ),
    (
        'Black Label Trading Co',
        'Deliverance Nocturne',
        'Nicaragua',
        'Pennsylvania Broadleaf',
        'Full',
        'Salomon',
        94,
        '$$$',
        'Dark chocolate, licorice, black pepper',
        'Intense and visually striking with its dark wrapper.',
        ARRAY ['Nicaraguan', 'Artisanal', 'Intense'],
        ARRAY ['Porter', 'Turkish Coffee', 'Blackberries']
    ),
    (
        'Crux',
        'Epicure',
        'Nicaragua',
        'Connecticut',
        'Mild',
        'Robusto',
        91,
        '$$',
        'Cream, light vanilla, cedar',
        'A high-end mild cigar with great complexity.',
        ARRAY ['Nicaraguan', 'Mild', 'Complex'],
        ARRAY ['Chardonnay', 'Latte', 'Shortbread']
    ),
    (
        'Southern Draw',
        'Jacob''s Ladder',
        'Nicaragua',
        'Pennsylvania Broadleaf',
        'Full+',
        'Belicoso',
        95,
        '$$$',
        'Espresso, dark chocolate, red pepper',
        'One of the strongest cigars in the market today.',
        ARRAY ['Nicaraguan', 'Family-Owned', 'Powerhouse'],
        ARRAY ['Double IPA', 'Espresso', 'Dark Chocolate']
    ),
    (
        'HVC',
        'Cerro',
        'Nicaragua',
        'Habano',
        'Medium',
        'Toro',
        92,
        '$$',
        'Cedar, hay, baking spice',
        'Inspired by the old-school cigars of Havana.',
        ARRAY ['Nicaraguan', 'Old-School', 'Aromatic'],
        ARRAY ['Cuban Coffee', 'Aged Rum', 'Nuts']
    ),
    (
        'Aganorsa Leaf',
        'Signature Selection',
        'Nicaragua',
        'Corojo 99',
        'Full',
        'Belicoso',
        95,
        '$$$$',
        'Sweet spice, cedar, nuts, citrus',
        'Showcasing the incredible tobacco grown by Aganorsa.',
        ARRAY ['Nicaraguan', 'Tabacalera', 'Complex'],
        ARRAY ['Bourbon', 'French Press', 'Dried Fruit']
    ),
    (
        'San Cristobal',
        'Revelation',
        'Nicaragua',
        'Ecuador Sumatra',
        'Medium',
        'Legend',
        93,
        '$$$',
        'Caramel, nuts, cedar, milk chocolate',
        'Smooth and creamy with a beautiful Sumatra wrapper.',
        ARRAY ['Nicaraguan', 'Sumatra', 'Creamy'],
        ARRAY ['Craft Lager', 'Cappuccino', 'Milk Chocolate']
    ),
    (
        'La Aroma de Cuba',
        'Mi Amor',
        'Nicaragua',
        'Mexican San Andres',
        'Full',
        'Ducale',
        95,
        '$$$',
        'Dark cocoa, almond, black pepper',
        'Rich and complex with a decadent Mexican wrapper.',
        ARRAY ['Nicaraguan', 'San-Andres', 'Rich'],
        ARRAY ['Zinfandel', 'Mocha', 'Steak']
    ),
    (
        'Punch',
        'Rare Corojo',
        'Honduras',
        'Ecuador Sumatra',
        'Medium',
        'Rothschild',
        91,
        '$$',
        'Nuttiness, cedar, sweet spice',
        'A limited annual release with a rich, reddish wrapper.',
        ARRAY ['Honduran', 'Seasonal', 'Classic'],
        ARRAY ['Amber Ale', 'Coffee', 'Pretzels']
    ),
    (
        'Alec Bradley',
        'Gatekeeper',
        'Dominican Republic',
        'Ecuador Habano',
        'Medium',
        'Robusto',
        94,
        '$$$',
        'Leather, baking spice, chocolate',
        'A collaboration with the Perez-Carrillo family.',
        ARRAY ['Dominican', 'Collaborative', 'Balanced'],
        ARRAY ['Pinot Noir', 'Cafe Latte', 'Vanilla Bean']
    ),
    (
        'CAO',
        'Flathead',
        'Nicaragua',
        'Connecticut Broadleaf',
        'Full',
        'V660 Carb',
        95,
        '$$$',
        'Black pepper, chocolate, earth',
        'Inspired by hot rods and pin-up girls. Box-pressed power.',
        ARRAY ['Nicaraguan', 'Box-Pressed', 'Bold'],
        ARRAY ['Jack Daniels', 'Strong Espresso', 'Beef Stew']
    ),
    (
        'Nica Rustica',
        'El Brujito',
        'Nicaragua',
        'Connecticut Broadleaf',
        'Full',
        'Toro',
        90,
        '$',
        'Charred wood, spice, earth',
        'A gritty, rustic cigar with deep broadleaf flavors.',
        ARRAY ['Nicaraguan', 'Rustic', 'Value'],
        ARRAY ['Stout Beer', 'Black Coffee', 'Beef Jerky']
    ),
    (
        'Brick House',
        'Maduro',
        'Nicaragua',
        'Brazilian Arapiraca',
        'Medium',
        'Robusto',
        91,
        '$',
        'Cocoa, sweet cedar, nuttiness',
        'A great value cigar with a unique Brazilian wrapper.',
        ARRAY ['Nicaraguan', 'Value', 'Maduro'],
        ARRAY ['Dark Beer', 'Iced Coffee', 'Peanuts']
    ),
    (
        'Nub',
        '460 Cameroon',
        'Nicaragua',
        'Cameroon',
        'Medium',
        'Nub',
        92,
        '$$',
        'Nutty, sweet woody, cedar',
        'Short and stout, designed to hit the "sweet spot" immediately.',
        ARRAY ['Nicaraguan', 'Short', 'Sweet'],
        ARRAY ['Tea', 'Coffee', 'Biscuits']
    ),
    (
        'Esteban Carreras',
        'Mr. Brownstone',
        'Nicaragua',
        'Connecticut Broadleaf',
        'Full',
        'Speedway',
        93,
        '$$$',
        'Dark chocolate, coffee, heavy spice',
        'Deeply rich and satisfying maduro.',
        ARRAY ['Nicaraguan', 'Broadleaf', 'Rich'],
        ARRAY ['Cognac', 'Espresso', 'Dark Chocolate Cake']
    ),
    (
        'Kristoff',
        'Vengeance',
        'Dominican Republic',
        'Connecticut Broadleaf',
        'Full',
        'Perfecto',
        91,
        '$$$',
        'Espresso, leather, spice',
        'A bold, oily cigar with an ancient look.',
        ARRAY ['Dominican', 'Rustic', 'Full-Bodied'],
        ARRAY ['Red Wine', 'Black Coffee', 'BBQ']
    ),
    (
        'My Father',
        'The Judge',
        'Nicaragua',
        'Ecuador Sumatra',
        'Full',
        'Grand Robusto',
        95,
        '$$$$',
        'Chocolate, nutty nancy, pepper',
        'A thick, substantial cigar with layers of flavor.',
        ARRAY ['Nicaraguan', 'Large-Gauge', 'Complex'],
        ARRAY ['Bourbon', 'French Press', 'Dark Chocolate']
    ),
    (
        'Liga Privada',
        'H99 Connecticut Corojo',
        'Nicaragua',
        'Connecticut Corojo',
        'Full',
        'Toro',
        96,
        '$$$$$',
        'Sweet spice, earth, leather',
        'A rare hybrid wrapper that delivers exceptional flavor.',
        ARRAY ['Nicaraguan', 'Hybrid-Wrapper', 'Luxury'],
        ARRAY ['High-End Rum', 'Espresso Martini', 'Premium Steaks']
    ),
    (
        'Plascencia',
        'Alma del Campo',
        'Nicaragua',
        'Nicaraguan',
        'Medium',
        'Sendero',
        94,
        '$$$$',
        'Creamy, nutty, coffee, vanilla',
        'Balanced and smooth, showcasing Plasencia''s farm tobacco.',
        ARRAY ['Nicaraguan', 'Balanced', 'Refined'],
        ARRAY ['White Wine', 'Latte', 'Shortbread']
    ),
    (
        'Davidoff',
        'Winston Churchill',
        'Dominican Republic',
        'Ecuador Habano',
        'Medium',
        'Commander',
        94,
        '$$$$$',
        'Creamy, cedar, pepper, nuts',
        'A versatile blend that is both elegant and complex.',
        ARRAY ['Dominican', 'Churchill', 'Elegant'],
        ARRAY ['Scotch', 'Earl Grey', 'Smoked Salmon']
    ),
    (
        'Arturo Fuente',
        'Hemingway Short Story',
        'Dominican Republic',
        'Cameroon',
        'Medium',
        'Perfecto',
        93,
        '$$',
        'Sweet wood, nuttiness, spice',
        'The perfect 30-minute smoke with a sweet Cameroon wrapper.',
        ARRAY ['Dominican', 'Small', 'Classic'],
        ARRAY ['Espresso', 'Port', 'Crackers']
    );