CREATE TABLE IF NOT EXISTS cigars (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand TEXT NOT NULL,
    name TEXT NOT NULL,
    origin TEXT,
    wrapper TEXT,
    strength TEXT,
    size TEXT,
    rating INTEGER,
    price TEXT,
    notes TEXT,
    description TEXT,
    tags TEXT [],
    pairings TEXT [],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Enable Row Level Security (RLS)
ALTER TABLE cigars ENABLE ROW LEVEL SECURITY;
-- Create policy to allow anyone to read
CREATE POLICY "Allow public read access" ON cigars FOR
SELECT USING (true);
-- Insert initial data
INSERT INTO cigars (
        brand,
        name,
        origin,
        wrapper,
        strength,
        size,
        rating,
        price,
        notes,
        description,
        tags,
        pairings
    )
VALUES (
        'Cohiba',
        'Behike 52',
        'Cuba',
        'Colorado Maduro',
        'Full',
        'Robusto Extra',
        98,
        '$$$$$',
        'Cedar, espresso, dark chocolate, leather',
        'The pinnacle of Cuban craftsmanship. Behike uses a unique medio tiempo leaf — the rarest tobacco in the world.',
        ARRAY ['Cuban', 'Ultra-Premium', 'Aged'],
        ARRAY ['Aged Rum', 'Espresso', 'Port Wine']
    ),
    (
        'Padron',
        '1964 Anniversary Natural',
        'Nicaragua',
        'Colorado Claro',
        'Full',
        'Churchill',
        96,
        '$$$$',
        'Cocoa, cream, leather, spice',
        'Celebrating over 50 years of Padron excellence. Sun-grown wrappers over aged Nicaraguan fillers.',
        ARRAY ['Nicaraguan', 'Anniversary', 'Classic'],
        ARRAY ['Bourbon', 'Dark Chocolate', 'Turkish Coffee']
    ),
    (
        'Arturo Fuente',
        'Opus X',
        'Dominican Republic',
        'Rosado',
        'Full',
        'Fuente Fuente',
        97,
        '$$$$',
        'Floral, cedar, pepper, cream',
        'The first Dominican puro with its own wrapper. A landmark achievement in cigar history.',
        ARRAY ['Dominican', 'Landmark', 'Premium'],
        ARRAY ['Single Malt Scotch', 'Cognac', 'Espresso']
    ),
    (
        'My Father',
        'Le Bijou 1922',
        'Nicaragua',
        'Oscuro',
        'Full+',
        'Torpedo',
        95,
        '$$$$',
        'Dark earth, roasted coffee, fig, leather',
        'Inspired by pre-Castro Cuban cigar traditions. Deeply complex and incredibly satisfying.',
        ARRAY ['Nicaraguan', 'Maduro', 'Bold'],
        ARRAY ['Rye Whiskey', 'Cold Brew', 'Madeira Wine']
    ),
    (
        'Davidoff',
        'Grand Cru No. 2',
        'Dominican Republic',
        'Colorado Claro',
        'Mild',
        'Lonsdale',
        94,
        '$$$$',
        'Creamy cedar, toasted oak, floral',
        'Davidoff''s benchmark of elegance. The ultimate expression of mild, refined smoking.',
        ARRAY ['Dominican', 'Mild', 'Elegant', 'Beginner-Friendly'],
        ARRAY ['Champagne', 'White Tea', 'Latte']
    ),
    (
        'Montecristo',
        'No. 2',
        'Cuba',
        'Colorado',
        'Medium',
        'Torpedo',
        95,
        '$$$',
        'Cedar, coffee, almond, subtle spice',
        'Perhaps the world''s most famous cigar. The No.2 torpedo is iconic — perfectly balanced.',
        ARRAY ['Cuban', 'Iconic', 'Balanced', 'Beginner-Friendly'],
        ARRAY ['Cuban Coffee', 'Añejo Tequila', 'Sherry']
    ),
    (
        'Rocky Patel',
        'Vintage 1990',
        'Honduras',
        'Connecticut Shade',
        'Mild',
        'Robusto',
        91,
        '$$',
        'Cream, mild wood, light pepper',
        'Buttery smooth with excellent construction. Perfect for those beginning their cigar journey.',
        ARRAY ['Honduran', 'Mild', 'Value', 'Beginner-Friendly'],
        ARRAY ['Light Beer', 'Cappuccino', 'Sparkling Water']
    ),
    (
        'Drew Estate',
        'Liga Privada No. 9',
        'Nicaragua',
        'Brazilian Corojo',
        'Full',
        'Robusto',
        96,
        '$$$',
        'Dark chocolate, coffee, earth, barnyard',
        'Drew Estate''s magnum opus. The Brazilian wrapper delivers extraordinary complexity.',
        ARRAY ['Nicaraguan', 'Boutique', 'Bold'],
        ARRAY ['Stout Beer', 'Mezcal', 'French Press Coffee']
    ),
    (
        'Plasencia',
        'Alma Fuerte',
        'Nicaragua',
        'Nicaraguan Habano',
        'Full',
        'Conquistador',
        97,
        '$$$',
        'Dark cocoa, coffee bean, roasted nuts, pepper',
        'Made from the finest tobacco from 6 different Nicaraguan growing regions.',
        ARRAY ['Nicaraguan', 'Premium', 'Award-Winning'],
        ARRAY ['Armagnac', 'Double Espresso', 'Dark Rum']
    ),
    (
        'Romeo y Julieta',
        'Reserva Real',
        'Dominican Republic',
        'Ecuador Connecticut',
        'Medium',
        'Churchill',
        90,
        '$$',
        'Creaminess, subtle spice, dried fruit',
        'A refined daily smoker. Excellent entry point into the premium Dominican tradition.',
        ARRAY ['Dominican', 'Medium', 'Daily Smoker', 'Beginner-Friendly'],
        ARRAY ['Pinot Noir', 'Chai Latte', 'Amaretto']
    );